### ISSUE TITLE
录制视频和小视屏，点击开始button，就crash

### ISSUE THREAD

**Issue by FrameJack** [hui46226021/VideoDemo#1]
机子：三星 N9006
系统 android 5.0

**Comment by hui46226021** [comment]
能否看看 异常信息    或者是否是权限相关的问题

**Comment by FrameJack** [comment]
1.录制视频            
     //准备开始录制视频
                if (!prepareMediaRecorder()) {
                    Toast.makeText(VideoInputActivity.this, getString(R.string.camera_init_fail), Toast.LENGTH_SHORT).show();
                    setResult(RESULT_CODE_FOR_RECORD_VIDEO_FAILED);
                    releaseCamera();
                    releaseMediaRecorder();
                    finish();
                }

错误信息 ： Toast.makeText(VideoInputActivity.this, getString(R.string.camera_init_fail), 弹出Toast
类名：
VideoInputActivity.class

我看下是不是权限问题

**Comment by hui46226021** [comment]
短点看下 prepareMediaRecorder 里是否有报错  
![image](https://cloud.githubusercontent.com/assets/13247280/23244125/27319f08-f9be-11e6-977a-3dd6a9ced42e.png)应该有捕获 看 错误信息

**Comment by FrameJack** [comment]
错误捕捉没有，我刚刚看了下你的清单文件好像少了

<uses-permission android:name="android.permission.WRITE_EXTERNAL_STORAGE"/>
权限，加上去就好了

**Comment by hui46226021** [comment]
嗯

**Comment by hui46226021** [comment]
好了 你到是给个star
